env_variables: NEWS_API_KEY:"914feab18f1e4ed980866bee04de2266"
  AWS_ACCESS_KEY_ID:"AKIASR2CFILMBZDHJIWS"
  AWS_SECRET_ACCESS_KEY:"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"
  AWS_DEFAULT_REGION:"us-east-1"
  OPEN_AI_API_KEY:"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"
